# Change value of some pixels for some raster

In [1]:
import rasterio
import numpy as np

In [2]:
file = "/LUSTRE/MADMEX/tnc_data_steffen_thilo/tnc_marismas/marismasnacionales_coberturadesuelo_2019_nivel2_final_20190925.tif"

In [3]:
with rasterio.open(file) as src:
    array = src.read()
    unique_values = np.unique(array)
    if np.any(unique_values > 255):
        print("Raster has pixel values that are greater than 255 value, then either relabel it to have values under 255 and it can be written with a dtype of uint8 -uses less memory- or use different command line")   
    else:
        (unique, counts) = np.unique(array, return_counts=True)
        frequencies = np.asarray((unique, counts)).T

continue with registration in geonode


In [11]:
print(frequencies)

[[        0 619402283]
 [        8  19851102]
 [       11   9279440]
 [       26   3129843]
 [       27   4543740]
 [       28  36435802]
 [       29   1615838]
 [       30   5443540]
 [       31  18049360]
 [       80   8755045]
 [      110  22505468]
 [      270   5953989]
 [      280  37497533]
 [      310  22065977]]


## Change labels with values 270, 280 and 310 for writing raster in `uint8` this will consume less memory and register it in geonode

**Replacing 270 value with 111**

In [12]:
array = np.where(array == 270, 111, array)

In [13]:
(unique, counts) = np.unique(array, return_counts=True)

In [14]:
frequencies = np.asarray((unique, counts)).T

In [15]:
print(frequencies)

[[        0 619402283]
 [        8  19851102]
 [       11   9279440]
 [       26   3129843]
 [       27   4543740]
 [       28  36435802]
 [       29   1615838]
 [       30   5443540]
 [       31  18049360]
 [       80   8755045]
 [      110  22505468]
 [      111   5953989]
 [      280  37497533]
 [      310  22065977]]


**Replacing 280 value for 112**

In [16]:
array = np.where(array == 280, 112, array)

In [17]:
(unique, counts) = np.unique(array, return_counts=True)

In [18]:
frequencies = np.asarray((unique, counts)).T

In [19]:
print(frequencies)

[[        0 619402283]
 [        8  19851102]
 [       11   9279440]
 [       26   3129843]
 [       27   4543740]
 [       28  36435802]
 [       29   1615838]
 [       30   5443540]
 [       31  18049360]
 [       80   8755045]
 [      110  22505468]
 [      111   5953989]
 [      112  37497533]
 [      310  22065977]]


**Replacing 280 value for 112**

In [20]:
array = np.where(array == 310, 113, array)

In [21]:
(unique, counts) = np.unique(array, return_counts=True)

In [22]:
frequencies = np.asarray((unique, counts)).T

In [23]:
print(frequencies)

[[        0 619402283]
 [        8  19851102]
 [       11   9279440]
 [       26   3129843]
 [       27   4543740]
 [       28  36435802]
 [       29   1615838]
 [       30   5443540]
 [       31  18049360]
 [       80   8755045]
 [      110  22505468]
 [      111   5953989]
 [      112  37497533]
 [      113  22065977]]


In [24]:
source_meta = r.meta.copy()

In [26]:
source_meta

{'driver': 'GTiff',
 'dtype': 'int16',
 'nodata': None,
 'width': 22960,
 'height': 35476,
 'count': 1,
 'crs': CRS.from_epsg(32613),
 'transform': Affine(5.0, 0.0, 393227.5,
        0.0, -5.0, 2553657.5)}

In [40]:
source_meta.update({"dtype": rasterio.uint8,
                    "compress": "lzw"})

In [41]:
source_meta

{'driver': 'GTiff',
 'dtype': 'uint8',
 'nodata': None,
 'width': 22960,
 'height': 35476,
 'count': 1,
 'crs': CRS.from_epsg(32613),
 'transform': Affine(5.0, 0.0, 393227.5,
        0.0, -5.0, 2553657.5),
 'compress': 'lzw'}

In [32]:
array[0].shape

(35476, 22960)

In [34]:
array = array[0]

In [35]:
array.shape

(35476, 22960)

In [36]:
array = np.array(array, dtype = np.uint8)

In [37]:
array.dtype

dtype('uint8')

In [29]:
output_filename = "/LUSTRE/MADMEX/tnc_data_steffen_thilo/tnc_marismas/marismasnacionales_coberturadesuelo_2019_nivel2_final_20190925_relabeled.tif"

In [42]:
with rasterio.open(output_filename, 'w', **source_meta,
                   ) as dst:
    dst.write(array, 1)

In [43]:
r.close()